version: '3.8'
services:
  db:
    image: postgres:latest
    platform: linux/amd64
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

  cache:
    image: redis:latest
    platform: linux/amd64
    volumes:
      - redisdata:/var/lib/redis/data
    env_file:
      - .env

  web:
    build: .

#    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    volumes:
      - .:/code
    env_file:
      - .env


volumes:
  pgdata:
  redisdata: